### ISSUE TITLE
Out of Memory errors with DAML Runtime (sbt)

### ISSUE THREAD

**Issue by anthonylusardi-da** [digital-asset/daml-on-fabric#20]
So I've encountered this issue a few times, once when trying to run multiple sbt participant nodes from the same computer, and another just now when building a Katacoda scenario.

It seems the whole process in general of running Fabric + DAML Runtime (sbt) + DAML JSON-API + create-daml-app UI from a single computer is using too much memory.

Worth noting is that Katacoda only has 2 GB of memory.

Increasing memory to `sbt` by adding flags `-Xss2M -XX:MaxMetaspaceSize=1024M` has some improvement.

Perhaps there are places to save on memory usage somewhere? Or perhaps minimum requirements can be specified in the README?

```
15:57:40.892 INFO  c.d.p.a.s.t.TrackerMap - Registered tracker for submitter Key(create-daml-app,Alice)
Uncaught error from thread [DamlonFabricServer-akka.actor.default-dispatcher-11]: Metaspace, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[DamlonFabricServer]
java.lang.OutOfMemoryError: Metaspace
[error] (AsyncAppender-Worker-ASYNC) java.lang.OutOfMemoryError: Metaspace

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "AsyncAppender-Worker-ASYNC"
Uncaught error from thread [DamlonFabricServer-akka.actor.default-dispatcher-11]: java.lang.NoSuchMethodException: no such method: java.lang.invoke.MethodHandle.linkToStatic(Object,long,long,Object,Object,MemberName)Object/invokeStatic, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[DamlonFabricServer]
java.lang.InternalError: java.lang.NoSuchMethodException: no such method: java.lang.invoke.MethodHandle.linkToStatic(Object,long,long,Object,Object,MemberName)Object/invokeStatic
        at java.lang.invoke.MethodHandleStatics.newInternalError(MethodHandleStatics.java:130)
        at java.lang.invoke.DirectMethodHandle.makePreparedLambdaForm(DirectMethodHandle.java:221)
        at java.lang.invoke.DirectMethodHandle.preparedLambdaForm(DirectMethodHandle.java:194)
        at java.lang.invoke.DirectMethodHandle.preparedLambdaForm(DirectMethodHandle.java:183)
        at java.lang.invoke.DirectMethodHandle.make(DirectMethodHandle.java:89)
        at java.lang.invoke.MethodHandles$Lookup.getDirectMethodCommon(MethodHandles.java:1660)
        at java.lang.invoke.MethodHandles$Lookup.getDirectMethodNoSecurityManager(MethodHandles.java:1617)
        at java.lang.invoke.MethodHandles$Lookup.getDirectMethodForConstant(MethodHandles.java:1802)
        at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(MethodHandles.java:1751)
        at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:477)
        at com.daml.platform.apiserver.services.tracking.TrackerMap.$anonfun$cleanup$3(TrackerMap.scala:46)
        at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:370)
        at com.daml.platform.apiserver.services.tracking.TrackerMap.$anonfun$cleanup$2(TrackerMap.scala:44)
        at akka.actor.LightArrayRevolverScheduler$$anon$1$$anon$2.run(LightArrayRevolverScheduler.scala:110)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:47)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:47)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.NoSuchMethodException: no such method: java.lang.invoke.MethodHandle.linkToStatic(Object,long,long,Object,Object,MemberName)Object/invokeStatic
        at java.lang.invoke.MemberName.makeAccessException(MemberName.java:871)
        at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1003)
        at java.lang.invoke.DirectMethodHandle.makePreparedLambdaForm(DirectMethodHandle.java:219)
        ... 18 more
Caused by: java.lang.NoSuchMethodError: java.lang.invoke.MethodHandle.linkToStatic(Ljava/lang/Object;JJLjava/lang/Object;Ljava/lang/Object;Ljava/lang/invoke/MemberName;)Ljava/lang/Object;
        at java.lang.invoke.MethodHandleNatives.resolve(Native Method)
        at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:975)
        at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1000)
        ... 19 more
Caused by: java.lang.OutOfMemoryError: Metaspace
Exception in thread "Thread-3" java.lang.OutOfMemoryError: Metaspace
```

**Comment by anthonylusardi-da** [comment]
Okay one thing that helps avoiding this is splitting up the `sbt` command between the first run (which installs a lot of dependencies) and the one actually operating the DAML Runtime. To me this indicates that the dependency installation doesn't flush unused memory when it's done.

Currently doing the following:
```
sbt "run --port 6865 --role provision"
sbt "run --port 6865 --role time,ledger" -J-DfabricConfigFile=config-local.yaml -Xss2M -XX:MaxMetaspaceSize=1024M
```

**Comment by dasormeter** [comment]
@anthonylusardi-da for running this on katacoda i think we should opt for running from the docker container rather than doing dynamic sbt run - the sbt run is really only intended to rapidly iterate when you are changing code to daml-on-fabric but in this case really i think we just want a process we can invoke so a container should be sufficient.
