### ISSUE TITLE
Akka version mismatch

### ISSUE THREAD

**Issue by anthonylusardi-da** [digital-asset/daml-on-fabric#52]
When running daml-on-fabric 1.8.0 I get the following issue. This is happening on https://daml.com/learn/deploying-daml/daml-on-fabric/ step 6 when executing the command `sbt "run --port 6865 --role time,ledger" -J-DfabricConfigFile=config-local.yaml -Xss2M -XX:MaxMetaspaceSize=1024M`

`sdk-version` is set to `1.8.0-snapshot.20201208.5840.0.38455e8c` in daml.yaml.

```
No META-INF folder detected. Starting chaincode without any custom indexes
That's all folks!
Admin@org1.example.com private key: /root/daml-on-fabric/src/test/fixture/tmp/data/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/priv_sk
Admin@org1.example.com sign cert: /root/daml-on-fabric/src/test/fixture/tmp/data/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcerts/Admin@org1.example.com-cert.pem
[WARN] [12/09/2020 19:45:03.080] [run-main-0] [ManifestInfo(akka://DamlonFabricServer)] You are using version2.6.10 of Akka, but it appears you (perhaps indirectly) also depend on older versions of related artifacts. You can solve this by adding an explicit dependency on version 2.6.10 of the [akka-slf4j] artifacts to your project. See also: https://doc.akka.io/docs/akka/current/common/binary-compatibility-rules.html#mixed-versioning-is-not-allowed
19:45:03.165 ERROR c.d.r.ProgramResource - Shutting down because of an initialization error.
java.lang.IllegalStateException: You are using version 2.6.10 of Akka, but it appears you (perhaps indirectly) also depend on older versions of related artifacts. You can solve this by adding an explicit dependency on version 2.6.10 of the [akka-slf4j] artifacts to your project. See also: https://doc.akka.io/docs/akka/current/common/binary-compatibility-rules.html#mixed-versioning-is-not-allowed
        at akka.util.ManifestInfo.checkSameVersion(ManifestInfo.scala:176)
        at akka.util.ManifestInfo.checkSameVersion(ManifestInfo.scala:154)
        at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:1033)
        at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:1022)
        at akka.actor.ActorSystemImpl._start(ActorSystem.scala:1022)
        at akka.actor.ActorSystemImpl.start(ActorSystem.scala:1045)
        at akka.actor.ActorSystem$.apply(ActorSystem.scala:272)
        at akka.actor.ActorSystem$.apply(ActorSystem.scala:316)
        at akka.actor.ActorSystem$.apply(ActorSystem.scala:260)
        at com.daml.DamlOnFabricServer$$anon$1.$anonfun$acquire$1(DamlOnFabricServer.scala:78)
        at com.daml.logging.LoggingContext$.newLoggingContext(LoggingContext.scala:15)
        at com.daml.logging.LoggingContext$.newLoggingContext(LoggingContext.scala:18)
        at com.daml.DamlOnFabricServer$$anon$1.acquire(DamlOnFabricServer.scala:77)
        at com.daml.DamlOnFabricServer$$anon$1.acquire(DamlOnFabricServer.scala:74)
        at com.daml.resources.ProgramResource.$anonfun$run$2(ProgramResource.scala:29)
        at scala.util.Try$.apply(Try.scala:213)
        at com.daml.resources.ProgramResource.$anonfun$run$1(ProgramResource.scala:29)
        at com.daml.resources.ProgramResource.$anonfun$run$1$adapted(ProgramResource.scala:26)
        at com.daml.logging.LoggingContext$.newLoggingContext(LoggingContext.scala:15)
        at com.daml.logging.LoggingContext$.newLoggingContext(LoggingContext.scala:18)
        at com.daml.resources.ProgramResource.run(ProgramResource.scala:26)
        at com.daml.DamlOnFabricServer$.delayedEndpoint$com$daml$DamlOnFabricServer$1(DamlOnFabricServer.scala:179)
        at com.daml.DamlOnFabricServer$delayedInit$body.apply(DamlOnFabricServer.scala:46)
        at scala.Function0.apply$mcV$sp(Function0.scala:39)
        at scala.Function0.apply$mcV$sp$(Function0.scala:39)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
        at scala.App.$anonfun$main$1$adapted(App.scala:80)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at scala.App.main(App.scala:80)
        at scala.App.main$(App.scala:78)
        at com.daml.DamlOnFabricServer$.main(DamlOnFabricServer.scala:46)
        at com.daml.DamlOnFabricServer.main(DamlOnFabricServer.scala)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at sbt.Run.invokeMain(Run.scala:115)
        at sbt.Run.execute$1(Run.scala:79)
        at sbt.Run.$anonfun$runWithLoader$4(Run.scala:92)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
        at sbt.TrapExit$App.run(TrapExit.scala:257)
        at java.base/java.lang.Thread.run(Thread.java:834)

Exception: sbt.TrapExitSecurityException thrown from the UncaughtExceptionHandler in thread "scala-execution-context-global-84"
[error] Nonzero exit code: 1
[error] (Compile / run) Nonzero exit code: 1
[error] Total time: 65 s (01:05), completed Dec 9, 2020, 7:46:03 PM
```

**Comment by dasormeter** [comment]
@anthonylusardi-da this PR upgrades akka version to match DAML SDK : can you try this?  https://github.com/digital-asset/daml-on-fabric/pull/53

**Comment by dasormeter** [comment]
@anthonylusardi-da hopefully resolved by https://github.com/digital-asset/daml-on-fabric/pull/53 which has now been merged

**Comment by anthonylusardi-da** [comment]
That fixed it, thanks!
