### ISSUE TITLE
Installing on MacOS 11.1

### ISSUE THREAD

**Issue by glapworth** [digital-asset/daml-on-fabric#62]
Hi there,

I'm helping a colleague install daml-on-fabric and following the installation instructions from the README but I have hit a bit of a problem getting further than:

`sbt "run --port 6865 --role provision,time,ledger,explorer /Users/smithle/tmp3/quickstart/.daml/dist/quickstart-0.0.1.dar"`

Compilation happens as I would expect, until the end when I receive the following error:

```
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
[info] running com.daml.DamlOnFabricServer --port 6865 --role provision,time,ledger,explorer /Users/smithle/tmp3/quickstart/.daml/dist/quickstart-0.0.1.dar
log4j:WARN No appenders could be found for logger (org.hyperledger.fabric.sdk.helper.Config).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
[error] (run-main-0) java.lang.NullPointerException: Cannot read the array length because "<local7>" is null
[error] java.lang.NullPointerException: Cannot read the array length because "<local7>" is null
[error] at com.daml.FabricContext.getLocalUser(FabricContext.java:729)
[error] at com.daml.FabricContext.getOrgAdmin(FabricContext.java:714)
[error] at com.daml.FabricContext.<init>(FabricContext.java:88)
[error] at com.daml.DAMLKVConnector.<init>(DAMLKVConnector.java:74)
[error] at com.daml.DAMLKVConnector.get(DAMLKVConnector.java:30)
[error] at com.daml.DamlOnFabricServer$.delayedEndpoint$com$daml$DamlOnFabricServer$1(DamlOnFabricServer.scala:63)
[error] at com.daml.DamlOnFabricServer$delayedInit$body.apply(DamlOnFabricServer.scala:46)
[error] at scala.Function0.apply$mcV$sp(Function0.scala:39)
[error] at scala.Function0.apply$mcV$sp$(Function0.scala:39)
[error] at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
[error] at scala.App.$anonfun$main$1$adapted(App.scala:80)
[error] at scala.collection.immutable.List.foreach(List.scala:392)
[error] at scala.App.main(App.scala:80)
[error] at scala.App.main$(App.scala:78)
[error] at com.daml.DamlOnFabricServer$.main(DamlOnFabricServer.scala:46)
[error] at com.daml.DamlOnFabricServer.main(DamlOnFabricServer.scala)
[error] at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
[error] at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[error] stack trace is suppressed; run last Compile / bgRun for the full output
[error] Nonzero exit code: 1
[error] (Compile / run) Nonzero exit code: 1
[error] Total time: 3 s, completed 12 Jan 2021, 10:45:58
```

I have a feeling it's something to do with logging, but I'm not sure how to proceed.

Thanks for your help

**Comment by dasormeter** [comment]
hi @glapworth hmm this looks like it may be JDK version related?  are you on java 11 by any chance?  daml on fabric needs jdk8 to run

**Comment by glapworth** [comment]
Thanks for getting back to me @dasormeter. That sounds like a good point. I hadn’t realised that there might be a Java version mismatch. I’ll check with my colleague and see if that helps. I’ll close this issue for now.
